---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl : "http://vectorijk.github.io/"
languageCode : "en-us"
title : "vectorijk"
canonifyurls : true
...